#!/bin/bash
# Quick test of fallback strategy

cd /home/cc/EnvAgent-plus

echo "============================================================"
echo "FALLBACK STRATEGY TEST - Quick Start"
echo "============================================================"
echo ""
echo "To test the new fallback strategy with a real repo:"
echo ""
echo "1. Run a single test:"
echo "   bash test_fallback.sh"
echo ""
echo "2. Or run manually:"
echo "   source venv/bin/activate"
echo "   source config/CHI-251467-openrc-2.sh"
echo "   python 2.0/src/provision_v2.py --repo https://github.com/rayon-rs/rayon --site tacc"
echo ""
echo "3. For batch testing:"
echo "   SITE=tacc ./run_all_repos.sh"
echo ""
echo "============================================================"
echo "WHAT TO EXPECT"
echo "============================================================"
echo ""
echo "If compute_cascadelake is unavailable, you should see:"
echo ""
echo "  [Attempt 1/5] Primary: compute_cascadelake for 48h"
echo "      ✗ Failed: Not enough resources available"
echo "      Waiting 5s before next attempt..."
echo ""
echo "  [Attempt 2/5] Fallback: compute_cascadelake for 24h"
echo "      ✗ Failed: Not enough resources available"
echo "      Waiting 5s before next attempt..."
echo ""
echo "  [Attempt 3/5] Alt 1: compute_skylake (48h)"
echo "      ✓ Lease created and ACTIVE"
echo ""
echo "  Status: ✓ SUCCESS"
echo "  Node Type (requested): compute_cascadelake"
echo "  Node Type (actual):    compute_skylake"
echo ""
echo "============================================================"
echo "FILES CREATED/MODIFIED"
echo "============================================================"
echo ""
echo "New modules:"
echo "  ✓ 2.0/src/reservation_fallback.py"
echo "  ✓ 2.0/src/kvm_launcher.py"
echo ""
echo "Updated:"
echo "  ✓ 2.0/src/provision_v2.py"
echo "  ✓ run_all_repos.sh"
echo ""
echo "Documentation:"
echo "  ✓ FALLBACK_STRATEGY.md"
echo "  ✓ FALLBACK_QUICK_START.md"
echo "  ✓ IMPLEMENTATION_NOTES.md"
echo "  ✓ SOLUTION_SUMMARY.md"
echo "  ✓ STRATEGY_DIAGRAM.sh"
echo "  ✓ CHANGES_MANIFEST.txt"
echo ""
echo "============================================================"
echo "TEST LOGS"
echo "============================================================"
echo ""
echo "Logs will be saved to:"
echo "  logs_test/<timestamp>_<repo_name>.log"
echo ""
echo "To view results:"
echo "  tail logs_test/*.log"
echo "  grep 'Node Type (actual)' logs_test/*.log"
echo ""
